version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: imovies
      POSTGRES_PASSWORD: "tZDjlboUDPa2ZP5rl7DhjxEVmMY2zpfL"
    volumes:
      - imovies_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "a_bE2e5s-uueyD6JSfqf12WKFgRRt_Yc"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  imovies_data:
