name: imovies_flutter
description: A new Flutter project with Serverpod.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.5
  dio: ^5.5.0+1
  email_validator: any
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_inappwebview: ^6.0.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  freezed: ^2.5.2
  get_it: ^7.7.0
  glassmorphism: ^3.0.0
  go_router: ^14.2.3
  image_picker: ^1.1.2
  imovies_client:
    path: ../imovies_client
  intl: ^0.19.0
  lottie: ^3.1.2
  marquee: ^2.2.3
  pinput: ^5.0.0
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.3.5
  serverpod_auth_client: any
  serverpod_auth_email_flutter: ^2.0.2
  serverpod_auth_shared_flutter: ^2.0.2
  serverpod_flutter: ^2.0.2
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ">=3.0.0 <5.0.0"
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  youtube_player_flutter: ^9.0.2
dependency_overrides:
  fading_edge_scrollview: ^4.1.1
  shared_preferences: ^2.3.3
  pigeon: ^22.7.0


flutter_launcher_icons:
    android: true
    adaptive_icon: true
    adaptive_icon_monochrome: true
    android_icon_shape: "adaptive"
    image_path: "assets/images/movie-logo.jpg"
    android_icon_foreground: "assets/images/movie-logo.jpg"
    android_icon_background: "assets/images/movie-logo.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gifs/
    - assets/svgs/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Signika Negative
      fonts:
        - asset: assets/fonts/SignikaNegative-VariableFont_wght.ttf

    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-VariableFont_GRAD,wght.ttf
        - asset: assets/fonts/Signika-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
